run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Checking for unchecked errors
    - gosimple      # Simplify code
    - govet         # Reports suspicious constructs
    - ineffassign   # Detects ineffectual assignments
    - staticcheck   # Go static analysis
    - typecheck     # Type checking
    - unused        # Checks for unused constants, variables, functions and types
    - gofmt         # Checks if code is formatted
    - goimports     # Checks import statements are formatted
    - misspell      # Finds commonly misspelled English words
    - revive        # Fast, configurable, extensible, flexible, and beautiful linter for Go
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Reports unused function parameters
    - gosec         # Security problems
    - gocritic      # Most opinionated Go linter
    - prealloc      # Finds slice declarations that could potentially be preallocated
    - exportloopref # Checks for pointers to enclosing loop variables
    - nilerr        # Finds code that returns nil even if it checks that error is not nil
    - bodyclose     # Checks whether HTTP response body is closed successfully

  disable:
    - errchkjson    # Too strict for this project
    - exhaustive    # Exhaustiveness checks can be too strict
    - funlen        # Function length checks - not needed
    - gocognit      # Cognitive complexity - not needed for now
    - gocyclo       # Cyclomatic complexity - not needed for now
    - lll           # Line length - not enforced

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    check-shadowing: true
    disable:
      - fieldalignment  # Too noisy, not critical for correctness

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/queuebridge/tdtp

  misspell:
    locale: US

  revive:
    confidence: 0.8
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      # - name: indent-error-flow  # Too opinionated
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      # - name: unused-parameter  # Too noisy, often intentional for interface compliance
      - name: unreachable-code
      - name: redefines-builtin-id

  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104  # Audit errors not checked - handled by errcheck
      - G304  # File path provided as taint input - needed for file operations

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - commentFormatting
      - whyNoLint
      - unnamedResult
      # hugeParam is important for performance - keep enabled
    settings:
      hugeParam:
        sizeThreshold: 160  # Warn for structs > 160 bytes (2 cache lines)

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - gocritic
        - errcheck

    # Exclude known issues in generated files
    - path: ".*\\.pb\\.go"
      linters:
        - all

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
