database:
  type: postgres
  host: localhost
  port: 5433
  database: tdtp_branch
  user: tdtp
  password: tdtp
  schema: public
  sslmode: disable

broker:
  type: rabbitmq
  host: localhost
  port: 5672
  user: tdtp
  password: tdtp
  queue: tdtp.sync.guides
  durable: true
