package audit

import (
	"fmt"
	"os"
	"os/exec"
	"strings"
	"testing"
)

// childEnv makes the test binary emit one id and exit, so the parent can get
// an id that was generated by a genuinely different process.
const childEnv = "TDTP_AUDIT_ID_CHILD"

// TestGenerateIDUniqueWithinProcess covers the original bug: a coarse clock
// returning the same UnixNano for back-to-back calls.
func TestGenerateIDUniqueWithinProcess(t *testing.T) {
	const n = 10000

	seen := make(map[string]struct{}, n)
	for i := 0; i < n; i++ {
		id := generateID()
		if _, dup := seen[id]; dup {
			t.Fatalf("duplicate id after %d calls: %s", i, id)
		}
		seen[id] = struct{}{}
	}
}

// TestGenerateIDEmitChild is the child half of the test below. It is a no-op
// unless the parent asked for it.
func TestGenerateIDEmitChild(t *testing.T) {
	if os.Getenv(childEnv) == "" {
		t.Skip("child-only helper")
	}
	fmt.Println(generateID())
}

// TestGenerateIDDiffersAcrossProcesses covers the case the sequence cannot.
//
// Separate processes sharing one audit table each start at seq=1, and on a
// coarse clock several of them read the same UnixNano — eight tdtpcli runs
// launched together by one orchestrator step is exactly that shape. The ids
// collided and the losing inserts failed on the PRIMARY KEY, dropping audit
// entries precisely when the most work was running in parallel.
//
// This has to spawn a real second process: the nonce is package state
// initialised once, so nothing inside this process can produce a second one.
func TestGenerateIDDiffersAcrossProcesses(t *testing.T) {
	if testing.Short() {
		t.Skip("spawns a child process")
	}

	cmd := exec.Command(os.Args[0], "-test.run=^TestGenerateIDEmitChild$", "-test.v=false")
	cmd.Env = append(os.Environ(), childEnv+"=1")

	out, err := cmd.Output()
	if err != nil {
		t.Fatalf("child run: %v (output %q)", err, out)
	}

	var childID string
	for _, line := range strings.Split(string(out), "\n") {
		if strings.HasPrefix(strings.TrimSpace(line), "audit-") {
			childID = strings.TrimSpace(line)
			break
		}
	}
	if childID == "" {
		t.Fatalf("child emitted no id; output was %q", out)
	}

	// Same instant, same seq is the collision this guards. The ids must differ
	// anyway, because the last field belongs to the process.
	parent := generateID()
	if parent == childID {
		t.Fatalf("parent and child generated the same id: %s", parent)
	}

	pf, cf := strings.Split(parent, "-"), strings.Split(childID, "-")
	if len(pf) != 4 || len(cf) != 4 {
		t.Fatalf("want 4 dash-separated fields (audit, nanos, seq, nonce): %q / %q", parent, childID)
	}
	if pf[3] == cf[3] {
		t.Fatalf("both processes share nonce %q — two runs starting in the same clock tick would still collide", pf[3])
	}
}
