"""
Shared pytest fixtures for J_* and D_* API tests.
"""
from __future__ import annotations

from pathlib import Path

import pytest

from tdtp import TDTPClientDirect, TDTPClientJSON

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

TESTS_DIR   = Path(__file__).parent
TESTDATA    = TESTS_DIR / "testdata"
SAMPLE_FILE              = TESTDATA / "users.tdtp.xml"
NULLABLE_SAMPLE_FILE     = TESTDATA / "users_nullable.tdtp.xml"
COMPRESSED_SAMPLE_FILE   = TESTDATA / "users_compressed.tdtp.xml"

# Known sample data properties (kept in sync with users.tdtp.xml)
SAMPLE_TOTAL_ROWS    = 8
SAMPLE_FIELD_NAMES   = ["ID", "Name", "Email", "City", "Balance", "IsActive", "CreatedAt"]
SAMPLE_KEY_FIELD     = "ID"
# rows with Balance > 1000
SAMPLE_BALANCE_GT_1000_COUNT = 5
# rows where City = 'Moscow'
SAMPLE_MOSCOW_COUNT  = 2
# rows with Balance BETWEEN 1000 AND 2000 (inclusive)
SAMPLE_BETWEEN_1000_2000_COUNT = 3
# rows where Email LIKE 'john%'
SAMPLE_LIKE_JOHN_COUNT = 1
# rows where City IN ('Moscow', 'Omsk')
SAMPLE_IN_MOSCOW_OMSK_COUNT = 4

# Known nullable fixture properties (kept in sync with users_nullable.tdtp.xml)
NULLABLE_TOTAL_ROWS       = 4
NULLABLE_FIELD_NAMES      = ["ID", "Name", "City", "Balance"]
NULLABLE_NULL_CITY_COUNT  = 2   # rows where City IS NULL (empty string)
NULLABLE_NOT_NULL_CITY_COUNT = 2

# Known compressed fixture properties (kept in sync with users_compressed.tdtp.xml)
# Generated by: create_test_db.py → tdtpcli --export Users --compress
COMPRESSED_TOTAL_ROWS    = 10
COMPRESSED_TABLE_NAME    = "Users"


# ---------------------------------------------------------------------------
# Client fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(scope="session")
def j_client() -> TDTPClientJSON:
    """Shared TDTPClientJSON instance (stateless, safe to reuse)."""
    return TDTPClientJSON()


@pytest.fixture(scope="session")
def d_client() -> TDTPClientDirect:
    """Shared TDTPClientDirect instance (stateless, safe to reuse)."""
    return TDTPClientDirect()


# ---------------------------------------------------------------------------
# Sample file fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(scope="session")
def sample_tdtp_path() -> Path:
    """Path to the bundled sample .tdtp fixture."""
    if not SAMPLE_FILE.exists():
        pytest.skip(f"Sample fixture not found: {SAMPLE_FILE}")
    return SAMPLE_FILE


@pytest.fixture(scope="session")
def sample_data_j(j_client: TDTPClientJSON, sample_tdtp_path: Path) -> dict:
    """Pre-parsed sample data via JSON API (parsed once per session)."""
    return j_client.J_read(str(sample_tdtp_path))


@pytest.fixture(scope="session")
def nullable_tdtp_path() -> Path:
    """Path to the nullable fixture (has rows with empty City = NULL)."""
    if not NULLABLE_SAMPLE_FILE.exists():
        pytest.skip(f"Nullable fixture not found: {NULLABLE_SAMPLE_FILE}")
    return NULLABLE_SAMPLE_FILE


@pytest.fixture(scope="session")
def nullable_data_j(j_client: TDTPClientJSON, nullable_tdtp_path: Path) -> dict:
    """Pre-parsed nullable fixture via JSON API."""
    return j_client.J_read(str(nullable_tdtp_path))


@pytest.fixture(scope="session")
def compressed_tdtp_path() -> Path:
    """Path to the zstd-compressed fixture (generated by tdtpcli --compress)."""
    if not COMPRESSED_SAMPLE_FILE.exists():
        pytest.skip(f"Compressed fixture not found: {COMPRESSED_SAMPLE_FILE}")
    return COMPRESSED_SAMPLE_FILE


@pytest.fixture()
def tmp_tdtp(tmp_path: Path) -> Path:
    """A temporary path for writing .tdtp output files."""
    return tmp_path / "out.tdtp.xml"
